Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports ProyectoVB.Repositories
Imports ProyectoVB.Repositories.Mappers

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        ' *** Repositories ***
        Public ReadOnly UserRepository As MySqlUserRepository
        Public ReadOnly RoleRepository As MySqlRoleRepository
        Public ReadOnly PermissionRepository As MySqlPermissionRepository

        ' *** Mappers ***
        Private ReadOnly UserMapper As UserMapper
        Private ReadOnly RoleMapper As RoleMapper
        Private ReadOnly PermissionMapper As PermissionMapper

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses

            ' *** Mappers ***
            UserMapper = New UserMapper
            RoleMapper = New RoleMapper
            PermissionMapper = New PermissionMapper


            ' *** Repositories ***
            UserRepository = New MySqlUserRepository(UserMapper)
            RoleRepository = New MySqlRoleRepository(RoleMapper)
            PermissionRepository = New MySqlPermissionRepository(PermissionMapper)

        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = FrmPrincipal
            Me.MainForm.Hide()

            Dim login = New FrmLogin
            login.ShowDialog()
        End Sub


        Public Sub ShowMainForm()
            Me.MainForm.Show()
        End Sub

    End Class
End Namespace
