Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports ProyectoVB.Repositories
Imports ProyectoVB.Repositories.Mappers

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        ' *** Repositories ***
        Private _userRepository As MySqlUserRepository = Nothing
        Private _roleRepository As MySqlRoleRepository = Nothing
        Private _permissionRepository As MySqlPermissionRepository = Nothing
        Private _deletedUserRepository As MySqlDeletedUserRepository = Nothing

        ' *** Mappers ***
        Private _userMapper As UserMapper = Nothing
        Private _roleMapper As RoleMapper = Nothing
        Private _permissionMapper As PermissionMapper = Nothing
        Private _deletedUserMapper As DeletedUserMapper = Nothing

        Public ReadOnly Property UserRepository As MySqlUserRepository
            Get
                If _userRepository Is Nothing Then
                    _userMapper = New UserMapper()
                    _userRepository = New MySqlUserRepository(_userMapper)
                End If

                Return _userRepository
            End Get
        End Property

        Public ReadOnly Property RoleRepository As MySqlRoleRepository
            Get
                If _roleRepository Is Nothing Then
                    _roleMapper = New RoleMapper()
                    _roleRepository = New MySqlRoleRepository(_roleMapper)
                End If

                Return _roleRepository
            End Get
        End Property

        Public ReadOnly Property PermissionRepository As MySqlPermissionRepository
            Get
                If _permissionRepository Is Nothing Then
                    _permissionMapper = New PermissionMapper()
                    _permissionRepository = New MySqlPermissionRepository(_permissionMapper)
                End If

                Return _permissionRepository
            End Get
        End Property

        Public ReadOnly Property DeletedUserRepository As MySqlDeletedUserRepository
            Get
                If _deletedUserRepository Is Nothing Then
                    _deletedUserMapper = New DeletedUserMapper()
                    _deletedUserRepository = New MySqlDeletedUserRepository(_deletedUserMapper)
                End If

                Return _deletedUserRepository
            End Get
        End Property


        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = FrmLogin
        End Sub

    End Class
End Namespace
